spring:
  application:
    name: Gemini-apis
  datasource:
    url: ${MYSQL_URL}
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true



server:
  port: 8082

gemini:
  api:
    base-url: ${OPEN_API_URL}
    key: ${OPEN_API_KEY}


  thymeleaf:
    prefix: classpath:/templates/



